[general]
project_name = "yeee_test"

[morph]
specifications = "data/grating_design_specifications.txt"
positions = "data/grating_position.txt"
optimized_dir = "C:/Users/jse/Downloads/results_freeform_backup8/results_freeform_backup8"
image_name = "mat_props.png"
scale = 0.003
select_ids = ["N12_1", "N11_2"]

[morph.parameters]
train_epochs = 11
# im_sz = 1024
mp_sz = 96
warp_scale = 0.05
mult_scale = 0.4
add_scale = 0.4
add_first = false
